Feature/data generate
fearless-pioneer/simple-data-flow pull request #12
Opened 2023-10-03 07:23 UTC by Haeun-Oh

## Changes?

1. wget을 통해 data를 download 받은 후 압축을 풀어 csv파일을 minio에 업로드 합니다.
2. minio에 업로드된 데이터를 읽어 delta형태로 저장합니다.
## Test?

## Anything Else?
데이터 크기가 커서 상당히 오래 걸리네요..ㅠ

2023-10-06 14:52 UTC, dongminlee94 requested changes

2023-10-06 14:52 UTC, dongminlee94 commented on src/upload_parquet.py
> +(df.write.mode("overwrite").option("compression", "snappy").parquet("s3a://data/data.parquet"))
```suggestion
df.write.mode("overwrite").option("compression", "snappy").parquet("s3a://data/data.parquet")
```

2023-10-06 14:52 UTC, dongminlee94 commented on src/upload_parquet.py
> +# %%
```suggestion
```

2023-10-06 14:52 UTC, dongminlee94 commented on docker/data-generator/Dockerfile
> +    && rm -rf /tmp/*
boto3는 apt-get으로 설치하는게 아니라서 이렇게 하면 안될 것 같아요~

2023-10-06 14:52 UTC, dongminlee94 commented on docker/data-generator/Dockerfile
> +    && rm -rf /tmp/*
```suggestion
RUN pip install --no-cache-dir -U pip
    && pip install --no-cache-dir boto3==1.28.57
```

2023-10-06 15:26 UTC, Haeun-Oh commented on src/upload_parquet.py
> +(df.write.mode("overwrite").option("compression", "snappy").parquet("s3a://data/data.parquet"))
반영했습니다~

2023-10-06 15:26 UTC, Haeun-Oh commented on docker/data-generator/Dockerfile
> +    && rm -rf /tmp/*
반영했습니다~

2023-10-06 15:56 UTC, dongminlee94 requested changes

2023-10-06 15:56 UTC, dongminlee94 commented on docker/data-generator/Dockerfile
> +COPY data data
data라는 폴더 안에 "2019-Oct.csv", "2019-Dec.csv" 가 들어있어야하는거죠?

repo root path 아래에 data라는 폴더를 만드신건가요?

2023-10-06 15:56 UTC, dongminlee94 commented on docker/data-generator/data_generator.py
> +        )
```suggestion
def main():
    root_file_path = "./data"
    file_name_list = ["2019-Oct.csv", "2019-Dec.csv"]

    for file_name in file_name_list:
        local_csv_file_path = os.path.join(root_file_path, file_name)
        minio_file_path = os.path.join("raw", file_name)
        BOTO3_CLIENT.upload_file(
            local_csv_file_path,
            MINIO_BUCKET,
            minio_file_path,
        )
        
if __name__ == "__main__":
       main()
```
`def main():` 에 해당 코드 넣고, `if __name__ == "__main__":`에는 `main()` 만 남도록 하면 더 좋을 것 같아요!

2023-10-06 15:56 UTC, dongminlee94 commented on docker/data-generator/data_generator.py
> +        minio_file_path = os.path.join("raw", file_name)
마이너 한건데, os.path.join보다 f-string으로 표현하는건 어떠실까요?

2023-10-06 15:56 UTC, dongminlee94 commented on src/upload_parquet.py
> +df = spark.read.format("csv").load("s3a://data/", header=True)  # noqa: F821
이 부분 raw 추가안해도 되나요?

2023-10-07 00:04 UTC, Haeun-Oh commented on docker/data-generator/Dockerfile
> +COPY data data
다음과 같이 만들었습니다!
<img width="209" alt="image" src="https://github.com/fearless-pioneer/simple-data-flow/assets/69044270/086f68fb-7e66-456a-ba07-135f0d941f6b">

gitignore에 data폴더가 추가되어 있어 보이지가 않네욤

2023-10-07 00:07 UTC, Haeun-Oh commented on docker/data-generator/data_generator.py
> +        )
반영했습니다~

2023-10-07 00:07 UTC, Haeun-Oh commented on docker/data-generator/data_generator.py
> +        minio_file_path = os.path.join("raw", file_name)
반영했습니다~

2023-10-07 00:07 UTC, Haeun-Oh commented on src/upload_parquet.py
> +df = spark.read.format("csv").load("s3a://data/", header=True)  # noqa: F821
빼먹었네요
감사합니다! 반영했습니다~

2023-10-07 16:41 UTC, dongminlee94 commented on docker/data-generator/Dockerfile
> +COPY data data
아 그러면 이 내용을 당장에는 아니지만 어디 readme에 다가 적어두어야겠네요. 

그리고 저희 3명한테 공유만 해주시면 좋을 것 같아요~

저희도 그러면 다운로드 받아서 data-generator - data 폴더 안에 넣어두면 되겠군요 ㅎㅎ

2023-10-07 16:42 UTC, dongminlee94 requested changes

2023-10-07 16:42 UTC, dongminlee94 commented on docker/data-generator/data_generator.py
> +        local_csv_file_path = os.path.join(root_file_path, file_name)
```suggestion
        local_csv_file_path = f"./data/{file_name}"
```
이것도 이렇게 변경할 수 있을 것 같아요~

2023-10-07 16:42 UTC, dongminlee94 commented on docker/data-generator/data_generator.py
> +        local_csv_file_path = os.path.join(root_file_path, file_name)
이렇게 되면 root_file_path 변수는 삭제해도 되겠네요!

2023-10-08 05:01 UTC, Kimdongui commented on docker/data-generator/data_generator.py
> +        local_csv_file_path = os.path.join(root_file_path, file_name)
음 저는 하은님이 작성 해주신 것 처럼 명시적으로 남겨 두는 것이 좋아 보입니다. 누군가 코드를 사용하려고 봤을 때 더 직관적인 것 같아서 그렇습니다!

2023-10-08 05:50 UTC, Haeun-Oh commented on docker/data-generator/Dockerfile
> +COPY data data
README에 내용 추가해보았습니다. [90f2e93](https://github.com/fearless-pioneer/simple-data-flow/pull/12/commits/90f2e93218789ac79980d0a052a6540bcf695c6d)

2023-10-08 10:42 UTC, dongminlee94 commented on docker/data-generator/data_generator.py
> +        local_csv_file_path = os.path.join(root_file_path, file_name)
f-string으로 쓰는게 더 명시적이고 직관적이지 않나요?? `os.path.join(root_file_path, file_name)` 으로 쓰게 되면 `root_file_path` 같은 경우, 그 변수를 또 찾아서 시선을 옮겨야하는데, f-string을 쓰면 바로 그 string이 직관적으로 보여서요! 두 분 의견은 어떠신가요~?

2023-10-08 11:54 UTC, taeukkkim commented on docker/data-generator/data_generator.py
> +        local_csv_file_path = os.path.join(root_file_path, file_name)
개인적인 선호를 따지자면 전 f-string을 사용하지 않고 기존의 방법대로 한 뒤, `root_file_path`를 `path.py` 같이 한 파일에서 고정 경로를 모아두고 관리하는걸 선호하기는 합니다!
하지만 현재 상태에서 path가 여러개인 상황이 아니다보니, 이 코드에서는 f-string을 사용하는게 더 직관적으로 보이기는 합니다.

2023-10-08 11:56 UTC, dongminlee94 commented on docker/data-generator/data_generator.py
> +        local_csv_file_path = os.path.join(root_file_path, file_name)
오 좋습니다! 그러면 이 부분은 구현하신 하은님 취향대로 하시죠!

2023-10-08 11:56 UTC, dongminlee94 commented on docker/data-generator/data_generator.py
> +        local_csv_file_path = os.path.join(root_file_path, file_name)
resolve할게요~

2023-10-08 11:57 UTC, dongminlee94 approved these changes
LGTM

2023-10-08 12:03 UTC, merged