add: docker file of spark delta lake
fearless-pioneer/simple-data-flow pull request #4
Opened 2023-08-15 14:10 UTC by Haeun-Oh

## Changes?

delta lake를 사용할 수 있는 dockerfile을 추가합니다.
- delta lake docker hub: https://hub.docker.com/r/deltaio/delta-docker/tags
- apach spark-py docker hub: https://hub.docker.com/r/apache/spark-py/tags
- Dockerfile 작성에 참고한 gitbhub: https://github.com/delta-io/delta-docs/tree/main/static/quickstart_docker
- delta lake quick start: https://docs.delta.io/latest/quick-start.html#set-up-apache-spark-with-delta-lake
- roapi를 이용하여 delta table을 loading할 수 있다.
## Test?

2023-08-15 14:30 UTC, dongminlee94 commented
@Haeun-Oh 오 좋습니다! 이거 docker compose 이용해서 띄우도록 파일이 하나 작성되면 좋을 것 같아요!

References: https://github.com/fearless-pioneer/simple-data-flow/pull/3/files

2023-08-16 05:33 UTC, Haeun-Oh commented
동민님 혹시 docker compose를 사용하는 이유를 알 수 있을까요?
현재 작성한 PR 내용은 Dockerfile만으로도 충분해보여서 여쭤봅니다!
보통 docker compose는 여러 container를 한번에 띄울 때 사용하는 것으로 알고 있습니다.
> @Haeun-Oh 오 좋습니다! 이거 docker compose 이용해서 띄우도록 파일이 하나 작성되면 좋을 것 같아요!
> 
> References: https://github.com/fearless-pioneer/simple-data-flow/pull/3/files

2023-08-16 05:44 UTC, Haeun-Oh commented on DockerFile
> +# Note: Python version in this image is 3.10.6 and is available as `python3`.
저희 repo의 python 버전이 3.10이어서 spark-py Docer Image를 v3.4.0으로 선택했습니다.

2023-08-16 05:45 UTC, dongminlee94 commented
> 

@Haeun-Oh 오 맞아요. 이해하신 것이 맞습니다.
그런데 저희 spark도 master, worker로 이루어져서 container를 띄워야하고, history server도 띄워야하고, 나중에 yarn도 띄워야하고, 제가 카톡에서 말씀드렸던 api 서버도 하나 띄워야해요 ㅎㅎ 그래서 우선에 먼저 docker compose로 작성되면 좋을 것 같아요.

추가적으로, 현재 dockerfile로 spark가 master와 worker로 구분지어서 띄워지나요?

2023-08-16 05:51 UTC, Kimdongui commented
@Haeun-Oh 부가적인 이유는 크게 3가지라고 생각합니다.

1. 추후 시스템에 대한 확장성
2. 전체 시스템이 한번에 관리 되기 위함
3. 내부적으로 system to system이 같은 네트워크 상에 존재 해야하는 경우

2023-08-17 10:50 UTC, dongminlee94 requested changes

2023-08-17 10:50 UTC, dongminlee94 commented on Makefile
> +	docker compose -p delta down -v
```suggestion
spark-lake:
	docker compose -p spark -f docker-compose-spark.yml up -d

spark-clean:
	docker compose -p spark down -v
```

delta-lake보다 spark로 통일하면 좋을 것 같아요~

2023-08-17 10:50 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +version: '3.8'
```suggestion
version: '3'
```

elk와 통일시키면 좋을 것 같아요~

2023-08-17 10:50 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +      - "7077:7077"
```suggestion
      - 8080:8080
      - 7077:7077
```

따옴표 빼도 될 것 같아요~

2023-08-17 10:50 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +    image: bde2020/spark-master:3.1.1-hadoop3.2
```suggestion
    image: bde2020/spark-master:3.3.0-hadoop3.3
```

bde2020/spark-master:3.3.0-hadoop3.3 이 최신버전이더라구요. 변경하면 좋을 것 같아요.

2023-08-17 10:50 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +      - ./logs:/spark/logs
volume은 굳이 없어도 될 것 같아요~

2023-08-17 10:50 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +      - spark-network
network도 빼도 될 것 같아요~

2023-08-17 10:50 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +    image: bde2020/spark-worker:3.1.1-hadoop3.2
```suggestion
    image: bde2020/spark-master:3.3.0-hadoop3.3
```

2023-08-17 10:50 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +      - "8081:8081"
```suggestion
      - 8081:8081
```

2023-08-17 10:50 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +      - spark-network
```suggestion
```

2023-08-17 10:50 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +    image: deltaio/delta-docker:0.8.1_2.3.0_arm64
arm64로 하신 이유가 따로 있을까요?

2023-08-17 10:50 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +      - "9000:9000"
```suggestion
      - 9000:9000
```

2023-08-17 10:50 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +      - ./delta-lake:/delta
```suggestion
```

2023-08-17 10:50 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +      - spark-network
```suggestion
```

2023-08-17 10:50 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +  spark-network:
```suggestion
  simple-data-flow:
```

elk와도 연결시키도록 저희 레포 이름으로 가면 좋을 것 같아요.

2023-08-17 10:50 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +    command: ["--s3", "s3a://delta-lake"]
```suggestion
    command: ["--s3", "s3://delta-lake"]
```
a는 빼도 될 것 같아요. 이렇게 command를 치면 어떻게 되나요?

2023-08-20 00:15 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +      - ./logs:/spark/logs
혹시 volume이 굳이 없어도 되는 이유를 알 수 있을까요?
- local data 폴더에 저장해서 container의 data에 데이터를 넣고
- /spark/logs 폴더에 저장되는 log들을 local ./logs 폴더에서 쉽게 접근할 수 있을 것으로 보여서요!

먼저 제가 예상하는 동민님의 답변은
- 데이터를 spark를 활용해서 넣을 것이다.
- log는 다른 tool 사용해 확인할 것이다.
일 거 같네요!

2023-08-20 01:13 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +      - spark-network
저는 network가 필요하다고 생각합니다!
custom network를 명시해줘야 master가 worker를 발견하기 쉬울 거 같아요
동민님이랑 태욱님께서 spark web ui 가끔 안 뜰 때 있다고 하셨었지만 저는 연결이 문제 없이 잘되었던 것도 network 차이라고 생각합니다.

2023-08-20 01:14 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +    image: deltaio/delta-docker:0.8.1_2.3.0_arm64
제 local 환경이 mac이여서 선택했습니다!

2023-08-20 01:15 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +  spark-network:
network 이름을 변경하자는 말씀이실까요?

2023-08-20 01:18 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +    command: ["--s3", "s3a://delta-lake"]
s3a file system api를 사용하려고 추가하였습니다

2023-08-20 03:20 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +      - ./logs:/spark/logs
오 해주신 말씀도 맞고, 예상 답변도 일부 맞아요. 다만 volume은 필요할 때 넣자는 생각이었어요! log도 당장에 local에서 볼 만큼 필요하지 않을 것 같아서요~

2023-08-20 03:25 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +      - spark-network
음 다시 보니까 하은님 이거 맨 마지막에 network를 아래와 같이 변경해야할 것 같아요.

```yaml
networks:
  spark-network:
    driver: bridge
```

이게 아니라 default에 연결시켜야 할 것 같아요. 굳이 다른 network를 또 만들 필요가 없어서요.

```yaml
networks:
  default:
    name: simple-data-flow
```

이러면 문제도 없이 잘 뜰 것 같고, 굳이 container 안에 network를 명시하지 않아도 됩니다~

2023-08-20 03:26 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +    image: deltaio/delta-docker:0.8.1_2.3.0_arm64
음 이부분은 좀 자동화가 필요할 것 같아요. Dockerfile을 만들어서 os를 감지해서 base image를 x64와 arm64를 사용하도록 만들던지 해야할 것 같습니다. x64를 사용하는 사람들은 그러면 해당 이미지를 사용 못해서요

2023-08-20 03:27 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +  spark-network:
넵! 맞습니다~

2023-08-20 03:27 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +  spark-network:
모든 docker compose yaml 파일을 하나의 network에 연결시켜야해요~

2023-08-20 03:35 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +    command: ["--s3", "s3a://delta-lake"]
S3A가 아닌 S3를 사용하면 자체 하둡에서 S3의 저장소를 연결하여 객체를 직접 읽고 쓸 수 없나요? 제가 알기로는 아닌 것 같아서요.
그리고 보내주신 링크 봤는데 저희는 파일이 큰 경우 partitioning을 해서 delta가 알아서 넣을거라 상관없을 것 같아요!

2023-08-20 03:49 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +      - spark-network
FYI) compose를 띄우면 기본적으로 default라는 네트워크를 생성해요. 제가 하자는 방식은 그 default 네트워크의 이름만 변경하는 것이구요~ driver는 기본적으로 bridge를 사용하게 돼요. 이렇게 되면 각 container에 network를 따로 적어주지 않아도 되어요. 모든 container들은 기본적으로 default 네트워크에 연결이 되어요. 따라서 각 서비스의 networks에 네트워크를 별도로 명시할 필요가 없어요~

2023-08-21 08:11 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +version: '3.8'
혹시 elk docker compose 작성 시 3.8이 아닌 3.0을 사용하는 이유가 있을까요?
3.8이 최신으로 보입니다!

2023-08-21 13:57 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +      - spark-network
오오 그렇군요! 유용한 정보 감사합니다!!!!!!!🤩

2023-08-21 14:50 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +version: '3.8'
특별한 이유는 없었던 것 같아요 ㅋㅋ 보통 3을 써서 그랬던 것 같습니다. 혹시 저희가 3.8 버전 compose의 어떤 기능을 사용중인가요?

2023-08-21 14:51 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +version: '3.8'
앞서 질문드렸던 것은 궁금증에 여쭤본거구요! 3.8로 가도 상관없습니다~

2023-08-22 11:37 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +version: '3.8'
앗 저는 그냥 최신 버전을 선택한거였어서 여쭤봤습니다!ㅎㅎ

2023-08-22 11:42 UTC, Haeun-Oh commented on Makefile
> +	docker compose -p delta down -v
delta-lake와 spark 나눴습니다!

2023-08-22 11:43 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +      - "7077:7077"
뺐습니다~

2023-08-22 11:44 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +    image: bde2020/spark-master:3.1.1-hadoop3.2
[apache/spark docker hub](https://hub.docker.com/r/apache/spark)에서 최신 버전으로 선택했습니다!

2023-08-22 11:45 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +      - ./logs:/spark/logs
제거했습니다~

2023-08-22 11:45 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +    image: bde2020/spark-worker:3.1.1-hadoop3.2
완료했습니다~

2023-08-22 11:45 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +      - "8081:8081"
완료했습니다~

2023-08-22 11:46 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +      - spark-network
완료했습니다~

2023-08-22 11:46 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +      - "9000:9000"
완료했습니다~

2023-08-22 11:46 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +      - ./delta-lake:/delta
제거했습니다~

2023-08-22 11:46 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +      - spark-network
제거했습니다~

2023-08-22 11:47 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +  spark-network:
변경했습니다!

2023-08-22 11:47 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +    command: ["--s3", "s3a://delta-lake"]
넵 제거했습니다~

2023-08-22 14:20 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +    image: deltaio/delta-docker:0.8.1_2.3.0_arm64
uname -m을 사용해 감지할 수 있도록 수정해봤습니다!
[b1eecad](https://github.com/fearless-pioneer/simple-data-flow/pull/4/commits/b1eecada953c20cb7c987f20a8655c48139230e0)

2023-08-22 15:19 UTC, dongminlee94 commented on docker-compose-spark-delta-lake.yml
> +version: '3.8'
엇 하은님 이거는 3.8로 가시죠! 최신버전으로 가도 좋을 것 같아요 ㅎㅎ

2023-08-23 12:05 UTC, Haeun-Oh commented on docker-compose-spark-delta-lake.yml
> +version: '3.8'
앗 네! 반영했습니다~
[eaa3475](https://github.com/fearless-pioneer/simple-data-flow/pull/4/commits/eaa3475127c0221ba2ca128a516f1e13a18c5464)

2023-08-23 14:51 UTC, Haeun-Oh commented on docker-compose-spark.yml
> +services:
@dongminlee94 @taeukkkim spark 작성 완료하였습니다~
일단 driver container는 제거하였습니다!

2023-08-23 15:24 UTC, Haeun-Oh commented on docker-compose-delta-lake.sh
> +    image: minio/minio:RELEASE.2021-04-22T15-44-28Z
simple-data-ops를 참고했는데요 혹시 해당 버전을 사용한 이유가 있을까요?

2023-08-24 12:15 UTC, taeukkkim commented on docker-compose-spark.yml
> +      - SPARK_WORKER_WEBUI_PORT=8081
spark-worker 마다 port 번호 다르게 해줘야 할 것 같아요!

2023-08-24 12:15 UTC, taeukkkim commented on docker-compose-spark.yml
> +    container_name: spark-master
scala, java, r을 모두 사용하지 않고 python만 사용하는 것이라면 image를 `apache/spark:3.3.3-python3`를 사용해도 될 것 같습니다!

2023-08-24 12:54 UTC, dongminlee94 commented on docker-compose-delta-lake.sh
> +    image: minio/minio:RELEASE.2021-04-22T15-44-28Z
아 이거는 라이센스 때문에 그래요. 2021-04-22T15-44-28Z 이후 버전부터 라이센스가 아파치에서 이상한걸로 바뀌어요. runway도 그래서 minio 버전 이걸로 고정한 걸로 기억합니다!

2023-08-24 12:55 UTC, Haeun-Oh commented on docker-compose-spark.yml
> +      - SPARK_WORKER_WEBUI_PORT=8081
혹시 다르게 해줘야 하는 이유가 있을까요?
같아도 WEBUI는 잘 띄워져서요!

2023-08-24 12:55 UTC, Haeun-Oh commented on docker-compose-spark.yml
> +    container_name: spark-master
python만 사용하게 된다면 변경해도 좋을 거 같네요~

2023-08-24 14:27 UTC, Haeun-Oh commented on docker-compose-spark.yml
> +    container_name: spark-master
반영했습니다~[8cec0a7](https://github.com/fearless-pioneer/simple-data-flow/pull/4/commits/8cec0a78e6013f178c45480a04ff525877a14d86)

2023-08-24 14:27 UTC, Haeun-Oh commented on docker-compose-spark.yml
> +      - SPARK_WORKER_WEBUI_PORT=8081
그럼 해당 comment는 resolve해도 되는 걸까요?

2023-08-24 14:31 UTC, Haeun-Oh commented on docker-compose-spark.yml
> -  jupyterlab:
@taeukkkim 일단 jupyterlab관련 코드 제거했습니다~ 따로 만들어주시면 될거 같아요~

2023-08-25 02:48 UTC, dongminlee94 requested changes

2023-08-25 02:48 UTC, dongminlee94 commented on Makefile
> +	rm -rf docker-compose-delta-lake.yml
```suggestion
delta:
	bash docker-compose-delta.sh
	docker compose -p delta -f docker-compose-delta.yml up -d

delta-clean:
	docker compose -p delta down -v
	rm -rf docker-compose-delta.yml
```

짧게 delta는 어떠신지 여쭤봅니다! 
make 명령어 사용할 때는 확실히 짧은게 좋더라구요..
의견 주세용~

2023-08-25 02:48 UTC, dongminlee94 commented on docker-compose-delta-lake.sh
> +EOF
```suggestion
EOF
```

한칸 제거해도 될 것 같아요~

2023-08-25 02:49 UTC, dongminlee94 commented
@Haeun-Oh 하은님 추가적으로 health check 하는 부분은 없어도 될까요? 보니까 spark docker compose는 depends_on에 모두 master가 있는데 master가 잘 띄워졌는지 확인된 다음에 다른 서비스들을 띄워야하지 않을까해서요!

2023-08-26 23:59 UTC, Haeun-Oh commented on Makefile
> +	rm -rf docker-compose-delta-lake.yml
네 반영했습니다~

2023-08-27 00:00 UTC, Haeun-Oh commented on docker-compose-delta-lake.sh
> +EOF
반영했습니다~

2023-08-28 11:40 UTC, Haeun-Oh commented
> @Haeun-Oh 하은님 추가적으로 health check 하는 부분은 없어도 될까요? 보니까 spark docker compose는 depends_on에 모두 master가 있는데 master가 잘 띄워졌는지 확인된 다음에 다른 서비스들을 띄워야하지 않을까해서요!

spark-master container에 대해서 healthcheck 추가했습니다![cb7d1d4](https://github.com/fearless-pioneer/simple-data-flow/pull/4/commits/cb7d1d49c58c51091e13b8dd1558eededb3f45d8)

2023-08-28 12:37 UTC, dongminlee94 approved these changes
LGTM

2023-08-29 00:38 UTC, merged